package com.lumertz.cripto

val DATABASE_NAME = "cryptos.db"
val DATABASE_VERSION = 2
val TABLE_CRYPTO_TRANSACTIONS = "CRYPTO_TRANSACTIONS"
val CRYPTO_TRANSACTIONS_ID = "ID"
val CRYPTO_TRANSACTIONS_NAME = "NAME"
val CRYPTO_TRANSACTIONS_CODE = "CODE"
val CRYPTO_TRANSACTIONS_AMOUNT = "AMOUNT"
val CRYPTO_TRANSACTIONS_VALUE = "VALUE"
val CRYPTO_TRANSACTIONS_TOTAL = "TOTAL"
val CRYPTO_TRANSACTIONS_DATE = "DATE"